### ISSUE TITLE
Add customization for which artifact is selected

### ISSUE THREAD

**Issue by Corecii** [rojo-rbx/rokit#34]
### Incentive
Most releases are formatted well for pulling in binaries with rokit, especially ones built for its ecosystem. Some tools from outside the ecosystem are _well packaged_ for automatic downloads _but have incompatible names or zip structures_.

### Proposed Solution
To support these without having to build a repackaging cron job, I suggest:
- Custom regex pattern for release name matching on each supported platform
- Custom glob or regex pattern for executable finding on each supported platform
- Custom name for the executable when placed on the system. Some tools, like [cargo-make](https://github.com/sagiegurari/cargo-make) only work correctly if the executable is named correctly.

A fully-specified configuration could look something like this:

```toml
[tools.makers]
source = "sagiegurari/cargo-make@0.37.13"
bin_name = "makers"

[[tools.makers.targets]]
platforms = [ "windows_x64", "windows_x86" ]
release = ".*x86_64-pc-windows.*"
file = "**/makers.exe"

[[tools.makers.targets]]
platforms = [ "linux_x64", "linux_x86" ]
release = ".*x86_64-unknown-linux.*"
file = "**/makers"
```

In this example, the following fields are optional:
- `release`: if it's missing, we still use the target entry for finding the file, but we use the default release name matcher for the current platform.
- `file`: if it's missing, we still use the target entry for finding the release, but we use the default file finder for the current platform.
- `bin_name`: if it's missing, we use the default bin name.

This is not a perfect example of _why_ this is needed: `cargo-make` only _needs_ the `file` target customization to make sure rokit pulls `makers.exe` and not `cargo-make.exe` which both come in the same zip file. Still, it's a good example _of the configuration format_.

### Tricky Details
For customizing the bin name, rokit already creates a unique folder for each version of a tool. Using a different name for the exe shouldn't cause any naming conflicts. If the user ends up with two copies of a tool because one manifest specifies the bin_name and the other does not, they can exist just fine in the same folder. The only waste is disk space, but if you're setting bin_name, it's probably because the tool only works if it's named properly, so you'll only have one properly named tool anyways.

For customizing _everything else_, it could create conflicts between manifests if two manifests ask for the same tool from the same repo with the same version but specify different artifact targets. I'm not sure what the best move there is, other than more specific folder names. For example, hashing the resulting artifact name + relative file path and putting it here `.rokit\tool-storage\<user>\<repo>\<version>\<hash>` would work for ensuring uniqueness.

### Other Considerations
This is very close to being able to specify multiple files to be pulled in with a glob pattern. If we choose to do this, it may be worth leaving that route open, or just doing it from the very beginning. Some portable executables are lightweight and well-packaged, but they rely on some sibling libraries, especially on Windows. Not being able to pull these tools in with our toolchain manager because it can't just pull in a few extra files would be unfortunate!
