### ISSUE TITLE
Support more assets formats (lefthook)

### ISSUE THREAD

**Issue by meruiden** [rojo-rbx/rokit#72]
I'm trying to install lefthook for better pre-commit hook support, but rokit cant properly identify the right asset, but there are definitely assets that feel like they should be compatible:

https://github.com/evilmartians/lefthook/releases/tag/v1.7.14

```batch
> rokit add evilmartians/lefthook
ERROR Failed to extract contents for evilmartians/lefthook@1.7.14

Caused by:
    failed to extract artifact: unknown format
``` 

(I'm on windows)

**Comment by meruiden** [comment]
The problem seems to be that lefthook has both the raw executable unzipped, and as .gz zip. and Rokit seems to think the raw unzipped asset is the best option, but then it can't extract it because its not compressed. So either, Rokit should prioritize/sort on compressed file formats, zip, gz, tar gz, or it should support downloading executables from assets that aren't compressed

**Comment by meruiden** [comment]
Some background:
It would be awesome to support lefthook in the Roblox development workflow because it allows for easy pre-commit hooks for tools like selene and stylua without needing NPM for husky or pyhton for pre-commit[dot]com. Lefthook is a CLI tool without dependencies making it a great fit for the aftman/rokit style workflow for Rojo projects.

This is a great Lefthook config for a more professional workflow in Rojo:

lefthook.yml
```yml
pre-commit:
  commands:
    selene:
      glob: "*.{lua}"
      run: selene {staged_files}
    stylua:
      glob: "*.{lua}"
      run: stylua {staged_files}
      stage_fixed: true
```
